# Ingress configuration for the ui
# If you have installed ingress controller and want to expose application - set INGRESS.ENABLE to true.
# If you have some domain name set INGRESS.USEDOMAINNAME variable to true and set this fqdn to INGRESS.HOSTS
# If you don't have any domain names - set INGRESS.USEDOMAINNAME to false
ingress:
  enable: true
  usedomainname: true
  hosts:
    - reportportal.{{ ssm "/cls/DNS/Public/DomainName" }}
  annotations:
      external-dns.alpha.kubernetes.io/hostname: reportportal.{{ ssm "/cls/DNS/Public/DomainName" }}
      external-dns.alpha.kubernetes.io/scope: public
      kubernetes.io/ingress.class: nginx-rp
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 128m
      cert-manager.io/cluster-issuer:  "letsencrypt-rp"
      cert-manager.io/acme-challenge-type: http01
      kubernetes.io/tls-acme: "true"
  tls:
  - hosts:
    - reportportal.{{ ssm "/cls/DNS/Public/DomainName" }}
    secretName: reportportal-tls-secret
