apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: letsencrypt-rp
spec:
  acme:
    email: security@cls.com
    privateKeySecretRef:
      name: letsencrypt-rp
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx-rp